version: "3.7"
services:
  app:
    build:
      args:
        user: mehdi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bus-finder
    container_name: bus-finder-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bus-finder

  db:
    image: mysql:8.0
    volumes:
      - dbdata:/var/lib/mysql
    container_name: bus-finder
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - .env
    networks:
      - bus-finder

  nginx:
    image: nginx:alpine
    container_name: bus-finder-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - bus-finder
volumes:
  dbdata:
  
networks:
  bus-finder:
    driver: bridge
